<h1>Linear Algebra (CpE210A)

<h3> Laboratory 7 : Matrix Operations

<h5>Coded and submitted by:<i>
<h6>Nietes,Ralf Joshua M.<i>
<h5>201811752<i>
<h5>58011<i>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [67]:
A = np.array([
    [12,22,11],
    [4,15,6],
    [7,1,10]
])
B = np.array([
    [12,21,6],
    [8,5,9],
    [8,9,8]
])
C = np.array([
    [10,8,6],
    [20,17,12],
    [11,21,13]
])

<h4>Matrix Multiplication is not Commutative:$A \cdot B \neq B \cdot A$

In [68]:
A1=A@B
A2=B@A
print("AxB=\n",A1,"\n\nBxA=\n",A2)
np.array_equiv(A1,A2)

AxB=
 [[408 461 358]
 [216 213 207]
 [172 242 131]] 

BxA=
 [[270 585 318]
 [179 260 208]
 [188 319 222]]


False

<h4>Associative property of multiplication:
     $A \cdot (B \cdot C) = (A \cdot B) \cdot C$

In [69]:
B1=A@(B@C)
B2=(A@B)@C
print("Ax(BXC)=\n",B1,"\n\n(AxB)xC=\n",B2)
np.array_equiv(B1,B2)

Ax(BXC)=
 [[17238 18619 12634]
 [ 8697  9696  6543]
 [ 8001  8241  5639]] 

(AxB)xC=
 [[17238 18619 12634]
 [ 8697  9696  6543]
 [ 8001  8241  5639]]


True

<h4>Distributive properties:
    $A\cdot(B+C) = A\cdot B + A\cdot C$

In [70]:
C1=A@(B+C)
C2=(A@B)+(A@C)
print("Ax(B+C)=\n",C1,"\n\n(AxB)+(AxC)=\n",C2)
np.array_equiv(C1,C2)

Ax(B+C)=
 [[1089 1162  837]
 [ 622  626  489]
 [ 372  525  315]] 

(AxB)+(AxC)=
 [[1089 1162  837]
 [ 622  626  489]
 [ 372  525  315]]


True

<h4>Distributive properties:
    $(B+C)\cdot A = B\cdot A + C\cdot A$

In [74]:
D1=(B+C)@A
D2=(B@A)+(C@A)
print("(B+C)xA=\n",D1,"\n\n(BxA)+(CxA)=\n",D2)
np.array_equiv(D1,D2)

(B+C)xA=
 [[464 931 536]
 [571 967 650]
 [495 889 599]] 

(BxA)+(CxA)=
 [[464 931 536]
 [571 967 650]
 [495 889 599]]


True

<h4>Multiplicative identity property:
    $A\cdot I = A$

In [72]:
I = np.identity(3)
E1 = A@I
print("AxI=\n",E1,"\n\nA=\n",A)
np.array_equiv(A,E1)

AxI=
 [[12. 22. 11.]
 [ 4. 15.  6.]
 [ 7.  1. 10.]] 

A=
 [[12 22 11]
 [ 4 15  6]
 [ 7  1 10]]


True

<h4>Multiplicative property of zero:
    $A\cdot \emptyset = \emptyset$ 

In [73]:
zero_3 = np.zeros((3,3))
F1 = A@zero_3
print("Ax∅=\n",F1,"\n\n∅=\n",zero_3)
np.array_equiv(F1,zero_3) 

Ax∅=
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

∅=
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True